# Generated by Django 5.1.2 on 2024-11-29 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
    ]
