# Generated by Django 5.1.2 on 2024-11-30 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_report_status_remove_report_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
