# Generated by Django 5.1.2 on 2024-12-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
